import {ContextMap} from './ContextMap';
import React from 'react';
import {AbsoluteFill,Audio,Freeze,Img,OffthreadVideo,Sequence,interpolate,staticFile,useCurrentFrame} from 'remotion';
import {geoMercator,geoPath,geoCentroid} from 'd3-geo';
import type {FeatureCollection,Feature} from 'geojson';

type Scene={callout?:string;sourceLabel?:string;backgroundId?:string;location?:string;id:string;start:number;end:number;kind:string;heading:string;caption:string;layout:string;routes:boolean;asset?:{src:string;kind:string;trimStart:number;credit:{author:string;source:string}};chart?:{unit:string;source:string;values:{label:string;value:number}[]};map?:FeatureCollection};
export type Manifest={title:string;duration:number;fps:number;voice:string;scenes:Scene[]};
export const emptyManifest:Manifest={title:'Preview',duration:1,fps:30,voice:'',scenes:[]};
const ink='#143b36',cream='#f4f0e7',green='#a8efbe';
const tween=(f:number,start=0,length=22)=>interpolate(f,[start,start+length],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Background:React.FC<{scene:Scene}>=({scene})=>{const f=useCurrentFrame();if(!scene.asset)return null;const style={width:'100%',height:'100%',objectFit:'cover' as const};return <AbsoluteFill style={{overflow:'hidden'}}>{scene.asset.kind==='video'?<OffthreadVideo muted src={staticFile(scene.asset.src)} startFrom={Math.round(scene.asset.trimStart*30)} style={style}/>:<Img src={staticFile(scene.asset.src)} style={{...style,transform:`scale(${1+tween(f,0,(scene.end-scene.start)*30)*.06})`}}/>}<AbsoluteFill style={{background:'linear-gradient(0deg,rgba(8,32,28,.28),transparent 25%)'}}/></AbsoluteFill>};
const Geo:React.FC<{scene:Scene}>=({scene})=>{const f=useCurrentFrame();const map=scene.map!;const projection=geoMercator().fitExtent([[700,170],[1770,840]],map);const shape=geoPath(projection);const points=map.features.map(feature=>projection(geoCentroid(feature))!);return <svg width={1920} height={1080} style={{position:'absolute',inset:0}}><defs><marker id={`arrow-${scene.id}`} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#158069"/></marker></defs>{map.features.map((feature:Feature,i)=>{const p=points[i];return <g key={i}><path d={shape(feature)||''} fill={i===0?'#7aca9d':'#d9e0d3'} stroke={cream} strokeWidth={5}/>{scene.routes&&i>0&&<path d={`M${p[0]},${p[1]} L${p[0]+(points[0][0]-p[0])*tween(f,10+i*8,30)},${p[1]+(points[0][1]-p[1])*tween(f,10+i*8,30)}`} stroke="#158069" strokeWidth={5} markerEnd={`url(#arrow-${scene.id})`}/>}<circle cx={p[0]} cy={p[1]} r={7} fill={ink}/><text x={p[0]} y={p[1]+38} textAnchor="middle" fontSize={25} fontWeight={650} fill={ink} stroke={cream} strokeWidth={7} paintOrder="stroke">{String(feature.properties?.name||'')}</text></g>})}</svg>};
const Chart:React.FC<{scene:Scene}>=({scene})=>{const f=useCurrentFrame();const chart=scene.chart!;const max=['%','/100'].includes(chart.unit)?100:Math.max(...chart.values.map(v=>v.value),1);return <div style={{position:'absolute',left:820,top:220,width:950}}>{chart.values.map((v,i)=><div key={i} style={{marginBottom:42}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',marginBottom:14}}><span style={{fontSize:33,maxWidth:600}}>{v.label}</span><b style={{fontSize:48}}>{new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v.value*tween(f,10+i*7,28))}{chart.unit}</b></div><div style={{background:'#dce3d8',height:38,borderRadius:19,overflow:'hidden'}}><div style={{height:'100%',width:`${v.value/max*100*tween(f,10+i*7,28)}%`,background:'#16846d',borderRadius:19}}/></div></div>)}</div>};
const GraphicShot:React.FC<{scene:Scene;index:number}>=({scene,index})=>{const f=useCurrentFrame();const media=Boolean(scene.asset),graphic=scene.kind==='map'||scene.kind==='chart',split=media&&scene.layout==='split';const width=graphic?560:split?680:1450;return <AbsoluteFill style={{background:cream,color:media&&!split?'white':ink}}>{media&&(split?<div style={{position:'absolute',left:820,width:1100,height:1080}}><Background scene={scene}/></div>:<Background scene={scene}/>)}{scene.map&&<Geo scene={scene}/>} {scene.chart&&<Chart scene={scene}/>}<div style={{position:'absolute',left:110,top:graphic?180:scene.layout==='overlay'?580:210,width,opacity:tween(f),transform:`translateY(${(1-tween(f))*25}px)`,...(scene.layout==='overlay'&&media?{background:'rgba(12,48,41,.88)',padding:35,borderLeft:`7px solid ${green}`,width:1300}:{})}}><div style={{fontSize:22,letterSpacing:4,marginBottom:30,color:media&&!split?green:'#16846d'}}>ATLAS / {String(index+1).padStart(2,'0')}</div><div style={{fontSize:graphic?64:scene.heading.length>50?75:92,fontWeight:650,lineHeight:1.07}}>{scene.heading}</div>{scene.caption&&<div style={{fontSize:31,lineHeight:1.35,marginTop:30,maxWidth:graphic?550:1150,opacity:tween(f,12,20)}}>{scene.caption}</div>}</div><div style={{position:'absolute',left:110,bottom:70,right:110,fontSize:21,opacity:.85}}>{scene.asset?`${scene.asset.credit.source} · ${scene.asset.credit.author}`:scene.map?'Natural Earth · Country boundaries · Schematic directions, not travel routes':scene.chart?`Source: ${new URL(scene.chart.source).hostname}`:'Visual explanation'}</div></AbsoluteFill>};
const Shot:React.FC<{scene:Scene;index:number;scenes:Scene[];depth?:number}>=({scene,index,scenes,depth=0})=>{
 const f=useCurrentFrame(),duration=(scene.end-scene.start)*30;
 if(['map','explain'].includes(scene.kind)&&scene.map)return <AbsoluteFill><ContextMap map={scene.map} duration={duration}/>{scene.callout&&<div style={{position:'absolute',right:120,top:110,color:'white',fontSize:100,fontWeight:700,textShadow:'0 3px 12px #123',opacity:tween(f,20,20)}}>{scene.callout}</div>}</AbsoluteFill>;
 if(scene.kind==='explain'&&scene.map)return <AbsoluteFill style={{background:cream,color:ink}}><div style={{position:'absolute',left:100,top:80,fontSize:42,fontWeight:650}}>{scene.heading}</div>{scene.map.features.map((feature,i)=>{const total=scene.map!.features.length;const width=total===1?1100:760;const x=total===1?120:110+i*900;const projection=geoMercator().fitExtent([[x+70,260],[x+width-70,780]],feature);return <svg key={i} width={1920} height={1080} style={{position:'absolute',inset:0,opacity:tween(f,i*20,22)}}><path d={geoPath(projection)(feature)||''} fill="#7aca9d" stroke="#16846d" strokeWidth={4} style={{transform:`translateY(${Math.sin(f/60+i)*4}px)`}}/><text x={x+width/2} y={860} textAnchor="middle" fill={ink} fontSize={38}>{String(feature.properties?.name)}</text></svg>})}{scene.callout&&<div style={{position:'absolute',right:160,top:340,fontSize:160,fontWeight:700,color:'#16846d',opacity:tween(f,20,22),transform:`scale(${.8+.2*tween(f,20,22)})`}}>{scene.callout}</div>}<div style={{position:'absolute',left:100,bottom:55,fontSize:23}}>{scene.sourceLabel||'Country outlines · Natural Earth'}</div></AbsoluteFill>;
 if(scene.asset?.kind==='video')return <AbsoluteFill><Background scene={scene}/>{scene.location&&<div style={{position:'absolute',left:90,right:90,top:440,textAlign:'center',fontWeight:700,fontSize:86,color:'white',textShadow:'0 2px 8px #000',opacity:tween(f,5,15)*(1-tween(f,Math.min(90,duration-25),20))}}>{scene.location}</div>}<div style={{position:'absolute',right:60,bottom:40,fontSize:18,color:'white',textShadow:'0 1px 5px #000'}}>{scene.asset.credit.author} · {scene.asset.credit.source}</div></AbsoluteFill>;
 if(scene.asset?.kind==='image'){
  const previous=depth<3?scenes.slice(0,index).find(s=>s.id===scene.backgroundId):undefined;
  const enter=tween(f,3,22),drift=Math.sin(f/85)*5;
  return <AbsoluteFill style={{background:cream,color:ink}}>
   {previous?<AbsoluteFill style={{filter:`blur(${tween(f,0,22)*9}px)`,opacity:1-tween(f,0,22)*.4}}><Freeze frame={Math.max(0,Math.round((previous.end-previous.start)*30)-1)}><Shot scene={previous} index={scenes.indexOf(previous)} scenes={scenes} depth={depth+1}/></Freeze></AbsoluteFill>:<AbsoluteFill style={{background:'radial-gradient(ellipse at 20% 35%,#d1e2d6,transparent 65%),linear-gradient(130deg,#eee9de,#d7e2dd)'}}><div style={{position:'absolute',width:1200,height:1200,border:'2px solid #bacdc0',borderRadius:'50%',left:850+Math.sin(f/120)*15,top:-300}}/></AbsoluteFill>}
   <div style={{position:'absolute',left:290,top:120,width:1340,height:800,padding:18,boxSizing:'border-box',background:'#fffdf8',boxShadow:'0 28px 65px rgba(12,35,29,.3)',opacity:enter,transform:`translateY(${(1-enter)*70+drift}px) rotate(${(1-enter)*-3+Math.sin(f/110)*.35}deg) scale(${.96+.04*enter})`}}>
    <Img src={staticFile(scene.asset.src)} style={{width:'100%',height:scene.location?'91%':'100%',objectFit:'contain',background:'#f2efe8'}}/>
    {scene.location&&<div style={{fontSize:29,paddingTop:13,textAlign:'center',fontWeight:600}}>{scene.location}</div>}
   </div>
   <div style={{position:'absolute',left:90,bottom:42,right:90,fontSize:20}}>{scene.asset.credit.source} · {scene.asset.credit.author}</div>
  </AbsoluteFill>;
 }
 if(scene.kind==='title')return <AbsoluteFill style={{background:ink,color:cream,justifyContent:'center',padding:130}}><div style={{position:'absolute',left:100+f*1.5,top:180,width:Math.min(1500,300+f*5),height:4,background:green,opacity:.5}}/><div style={{fontSize:78,lineHeight:1.12,maxWidth:1400,transform:`translateX(${(1-tween(f))*40+Math.sin(f/100)*4}px)`}}>{scene.heading.split(' ').map((word,i)=><span key={i} style={{display:'inline-block',marginRight:20,opacity:tween(f,i*5,12),transform:`translateY(${(1-tween(f,i*5,12))*20}px)`}}>{word}</span>)}</div></AbsoluteFill>;
 return <GraphicShot scene={scene} index={index}/>;
};
export const AutomaticVideo:React.FC<{manifest:Manifest}>=({manifest})=><AbsoluteFill style={{fontFamily:'Segoe UI, Arial, sans-serif',background:cream}}>{manifest.voice&&<Audio src={staticFile(manifest.voice)}/>} {manifest.scenes.map((scene,index)=>{const from=Math.round(scene.start*30);return <Sequence key={scene.id} from={from} durationInFrames={Math.max(1,(index===manifest.scenes.length-1?Math.ceil(scene.end*30):Math.round(scene.end*30))-from)}><Shot scene={scene} index={index} scenes={manifest.scenes}/></Sequence>})}</AbsoluteFill>;
