import React from 'react';
import {AbsoluteFill,Audio,OffthreadVideo,Sequence,interpolate,staticFile,useCurrentFrame} from 'remotion';
import {geoMercator,geoPath} from 'd3-geo';
import countries from '../public/pilot/countries.json';

const ink='#143b36',green='#a8efbe',cream='#f4f0e7';
const progress=(f:number,start=0,d=24)=>interpolate(f,[start,start+d],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Label:React.FC<{children:React.ReactNode;light?:boolean}>=({children,light})=><div style={{fontSize:24,letterSpacing:5,fontWeight:600,color:light?green:ink}}>{children}</div>;
const Footage:React.FC<{id:string;start:number;dark?:number}>=({id,start,dark=.25})=><AbsoluteFill><OffthreadVideo muted src={staticFile(`pilot/${id}.mp4`)} startFrom={start*30} style={{width:'100%',height:'100%',objectFit:'cover'}}/><AbsoluteFill style={{background:`linear-gradient(90deg,rgba(5,27,26,${dark+.3}),rgba(5,27,26,${dark*.3}))`}}/></AbsoluteFill>;
const Intro=()=>{const f=useCurrentFrame();return <AbsoluteFill><Footage id="8211790" start={5} dark={.25}/><div style={{position:'absolute',left:110,top:170,opacity:progress(f),transform:`translateY(${(1-progress(f))*24}px)`}}><Label light>THE SMALL COUNTRY QUESTION</Label><h1 style={{fontSize:112,lineHeight:1.02,margin:'35px 0',fontWeight:650}}>Small country.<br/><span style={{color:green}}>Big numbers.</span></h1><div style={{fontSize:34,color:'#e0e9e2'}}>The Luxembourg commuter effect</div></div><div style={{position:'absolute',left:110,bottom:100,fontSize:24}}>LUXEMBOURG <span style={{opacity:.65}}> / real footage</span></div></AbsoluteFill>};
const Share=()=>{const f=useCurrentFrame();const p=progress(f,4,30);return <AbsoluteFill style={{background:cream,color:ink,padding:'110px'}}><Label>LUXEMBOURG'S WORKFORCE</Label><div style={{display:'flex',gap:100,alignItems:'center',marginTop:35}}><div style={{width:670}}><div style={{fontSize:208,fontWeight:700,letterSpacing:-12,lineHeight:1.05}}>≈{Math.round(47*p)}<span style={{fontSize:115}}>%</span></div><div style={{fontSize:53,lineHeight:1.1,marginTop:20}}>live across<br/>the border</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(10, 42px)',gap:16}}>{Array.from({length:100},(_,i)=><div key={i} style={{width:42,height:42,borderRadius:21,background:i<Math.round(47*p)?'#16846d':'#d6ddd5',transform:`scale(${.5+.5*progress(f,i*.15,15)})`}}/>)}</div></div><div style={{position:'absolute',bottom:98,left:110,fontSize:24,color:'#527068'}}>Approximate share • End of 2025 • Source: Luxembourg government</div></AbsoluteFill>};
const projection=geoMercator().center([5.8,49.85]).scale(13000).translate([1150,565]);
const path=geoPath(projection);
const MapScene=()=>{const f=useCurrentFrame();const target=projection([6.13,49.61])!;const origins:[string,[number,number],number][]=[['FRANCE',[5.6,48.9],15],['BELGIUM',[4.8,50.2],35],['GERMANY',[7.25,50.1],55]];return <AbsoluteFill style={{background:cream,color:ink}}><svg width="1920" height="1080" style={{position:'absolute'}}><defs><pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="#dce1d8" strokeWidth="1"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#138169"/></marker></defs><rect width="1920" height="1080" fill="url(#grid)"/>{countries.features.map(feature=><path key={feature.properties.ADMIN} d={path(feature as Parameters<typeof path>[0])||''} fill={feature.properties.ADMIN==='Luxembourg'?'#73c49a':'#e2e3d7'} stroke={cream} strokeWidth={5}/>)}{origins.map(([name,coord,delay])=>{const pt=projection(coord)!;const p=progress(f,delay,30);return <g key={name}><text x={pt[0]} y={pt[1]-40} textAnchor="middle" fill={ink} fontSize={27} fontWeight={650} letterSpacing={2}>{name}</text><circle cx={pt[0]} cy={pt[1]} r={7} fill={ink}/><path d={`M${pt[0]},${pt[1]} L${pt[0]+(target[0]-pt[0])*p},${pt[1]+(target[1]-pt[1])*p}`} stroke="#138169" strokeWidth={5} markerEnd={p>.03?'url(#arrow)':undefined}/></g>})}<circle cx={target[0]} cy={target[1]} r={10} fill={ink}/><rect x={target[0]-155} y={target[1]+30} width={310} height={63} rx={10} fill={ink}/><text x={target[0]} y={target[1]+72} textAnchor="middle" fill="white" fontSize={28} fontWeight={650}>LUXEMBOURG</text></svg><div style={{position:'absolute',left:110,top:120,width:530}}><Label>WORK ACROSS BORDERS</Label><h2 style={{fontSize:76,lineHeight:1.05,marginTop:30}}>Three neighbors.<br/>One workplace.</h2></div><div style={{position:'absolute',left:110,bottom:90,fontSize:22,color:'#527068'}}>Natural Earth boundaries • Arrows show direction, not travel routes</div></AbsoluteFill>};
const Output=()=>{const f=useCurrentFrame();return <AbsoluteFill><Footage id="8374061" start={2} dark={.15}/><div style={{position:'absolute',left:110,bottom:140,padding:'38px 50px',borderLeft:`8px solid ${green}`,background:'rgba(11,44,38,.86)',opacity:progress(f)}}><Label light>CROSS-BORDER WORKERS</Label><div style={{fontSize:66,marginTop:16}}>Their work adds to <span style={{color:green}}>GDP.</span></div></div></AbsoluteFill>};
const Equation=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:cream,color:ink,padding:110}}><Label>WHAT GDP PER CAPITA COUNTS</Label><div style={{display:'flex',alignItems:'center',gap:70,marginTop:110}}><div style={{width:900,textAlign:'center'}}><div style={{fontSize:65,fontWeight:650}}>Economic output</div><div style={{fontSize:29,color:'#158069',marginTop:18}}>Includes work done by cross-border commuters</div><div style={{height:4,background:ink,margin:'42px 0',transform:`scaleX(${progress(f,0,25)})`}}/><div style={{fontSize:65,fontWeight:650}}>Resident population</div><div style={{fontSize:29,marginTop:18,opacity:progress(f,10,25)}}>Excludes people who live abroad</div></div><div style={{fontSize:80}}>=</div><div style={{fontSize:66,width:440,lineHeight:1.12,color:'#158069'}}>GDP<br/>per capita</div></div><div style={{position:'absolute',left:110,bottom:95,fontSize:27,color:'#527068'}}>A measure of production per resident</div></AbsoluteFill>};
const Ending=()=>{const f=useCurrentFrame();return <AbsoluteFill><Footage id="8211790" start={30} dark={.45}/><div style={{position:'absolute',left:110,top:210,opacity:progress(f)}}><Label light>THE IMPORTANT DISTINCTION</Label><div style={{fontSize:106,lineHeight:1.05,fontWeight:650,marginTop:40}}>GDP per capita<br/><span style={{color:green}}>isn't your paycheck.</span></div><div style={{fontSize:32,marginTop:35}}>A wealthy economy does not make every resident wealthy.</div></div></AbsoluteFill>};
export const Pilot=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:'Segoe UI, Arial, sans-serif',color:'white',background:ink}}><Audio src={staticFile('pilot/narration.wav')}/><Sequence durationInFrames={171}><Intro/></Sequence><Sequence from={171} durationInFrames={108}><Share/></Sequence><Sequence from={279} durationInFrames={180}><MapScene/></Sequence><Sequence from={459} durationInFrames={126}><Output/></Sequence><Sequence from={585} durationInFrames={180}><Equation/></Sequence><Sequence from={765} durationInFrames={225}><Ending/></Sequence><div style={{position:'absolute',right:80,top:55,fontSize:22,letterSpacing:3,opacity:.75,color:f>=171&&f<459||f>=585&&f<765?ink:'white'}}>ATLAS / PILOT 01</div><div style={{position:'absolute',bottom:0,left:0,width:`${f/989*100}%`,height:5,background:green}}/><AbsoluteFill style={{background:ink,opacity:progress(f,976,13)}}/></AbsoluteFill>};
